spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: system
          uri: http://localhost:8091/system
          predicates:
            - Path = /system
        - id: custom
          uri: http://localhost:8092/custom
          predicates:
            - Path = /custom
server:
  port: 8099
